[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems <jo3mccain@scattered-systems.com>"]
description = "A zk-SNARK, Ethereum Native Multi-Chain engineered for optimal user experiences"
edition = "2021"
license = "MIT"
name = "aether"
repository = "https://github.com/scattered-systems/aether.git"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
bench = false
name = "aether"
path = "src/main.rs"
test = false

[dependencies]
aether_core = "0.1.0"
axum = "0.5.6"
bson = { features = ["chrono-0_4", "serde_with"], version = "2.2.0" }
hyper = { features = ["full"], version = "0.14.18" }
libp2p = "0.44.0"
serde = { features = ["derive"], version = "1.0.137" }
serde_json = "1.0.81"
tokio = { features = ["full"], version = "1.18.2" }
