[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems <jo3mccain@scattered-systems.com>"]
description = "A complete decentralized cloud storage solution"
edition = "2021"
license = "MIT"
name = "aether"
repository = "https://github.com/scattered-systems/chaos.git"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
bench = false
name = "aether"
path = "src/main.rs"
test = false

[dependencies]
