version: "4.0"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: latest
    container_name: backend
    depends_on:
      - cache
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /config:/config
      - /data:/data

  cache:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"
    restart: always


volumes:
  data: