[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
edition = "2021"
name = "aether_core"
repository = "https://github.com/scattered-systems/aether.git"
version = "0.1.0"

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[[test]]
path = "tests/simple.rs"

[dependencies]
