[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
edition = "2021"
name = "aether_core"
repository = "https://github.com/scattered-systems/aether.git"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
