version: "3.9"
services:
  application:
    build:
      context: ../$PROJECT_SLUG
      dockerfile: Dockerfile
    container_name: $PROJECT_SLUG

  cache:
    container_name: $PROJECT_SLUG-redis
    image: redis
    ports:
      - "6379:6379"
    restart: always

  mogno:
    container_name: $PROJECT_SLUG-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    image: mongo
    ports:
      - "27017:27017"
    restart: always

  database-postgres:
    container_name: $PROJECT_SLUG-postgresql
    environment:
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: example
    image: postgres
    ports:
      - "5432:5432"
    restart: always

volumes:
  data: